print("Find sem 4 SGPA")
math = int(input("Enter math gpa(3 credits): "))
database_mgmt = int(input("Enter Databae management gpa(4 credits): "))
iime = int(input("enter IIME gp(4 credits): "))
ada = int(input("Enter ADA gpa(3 credits): "))
fin_mgmt = int(input("Enter Financial Management gpa(3 credits): "))
uhv = int(input("Enter UHV gpa(1 credit): "))
mini_pro = int(input("Enter mini project gpa(1 credit): "))
ada_lab = int(input("Enter ADA lab gpa(1 credit): "))
SGPA = float((math*3 + database_mgmt*4 + iime*4 + ada*3 + fin_mgmt*3 + uhv + mini_pro + ada_lab)/20)
print(f"The resultant SGPA is {SGPA}: ")